
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.AadTokenResponse.resource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S103:Lines should not be too long", Justification = "<Pending>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.AadTokenResponse.access_token")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.AadTokenResponse.expires_in")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.AadTokenResponse.expires_on")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.AadTokenResponse.ext_expires_in")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.AadTokenResponse.not_before")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.AadTokenResponse.resource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.AadTokenResponse.token_type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.LogAnalyticsQuery.query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.LogAnalyticsQuery.timespan")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.LogAnalyticsQuery.query")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.LogAnalyticsQuery.timespan")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.AadTokenResponse.access_token")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.AadTokenResponse.expires_in")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.AadTokenResponse.expires_on")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.AadTokenResponse.ext_expires_in")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.AadTokenResponse.not_before")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.AadTokenResponse.resource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.AadTokenResponse.token_type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Column.name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Column.type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.LogAnalyticsQueryResponse.tables")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Table.columns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Table.name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Table.rows")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.AadTokenResponse.resource")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Column.name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Column.type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.LogAnalyticsQueryResponse.tables")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Table.columns")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Table.name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S100:Methods and properties should be named in PascalCase", Justification = "<Pending>", Scope = "member", Target = "~P:LogAnalytics.Client.Response.Table.rows")]