// <auto-generated />
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S2221:\"Exception\" should not be caught when not required by called methods", Justification = "<Pending>", Scope = "member", Target = "~M:Subscriptions.Console.Program.AddHooksToProjectsAsync(System.String,System.String,SecurePipelineScan.VstsService.IVstsRestClient,System.Collections.Generic.IEnumerable{Subscriptions.Console.ProjectInfo})~System.Threading.Tasks.Task")]